apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: travelowkey
  labels:
    app: api-gateway
    component: gateway
data:
  application.yml: |
    spring:
      application:
        name: api-gateway
      profiles:
        active: production,docker
      redis:
        host: redis
        port: 6379
        timeout: 2000ms
        lettuce:
          pool:
            max-active: 10
            max-idle: 8
            min-idle: 2
    
    server:
      port: 8080
      compression:
        enabled: true
      http2:
        enabled: true
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus,metrics
      endpoint:
        health:
          show-details: when_authorized
          probes:
            enabled: true
      health:
        circuitbreakers:
          enabled: true
        ratelimiters:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
        tags:
          environment: production
    
    resilience4j:
      circuitbreaker:
        instances:
          default:
            sliding-window-size: 10
            minimum-number-of-calls: 5
            failure-rate-threshold: 50
            wait-duration-in-open-state: 30s
      ratelimiter:
        instances:
          default:
            limit-for-period: 100
            limit-refresh-period: 1s
            timeout-duration: 0s
    
    logging:
      level:
        com.travelowkey: INFO
        org.springframework.cloud.gateway: INFO
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"