apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: travelowkey
  labels:
    app: api-gateway
    component: gateway
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: travelowkey
  name: api-gateway-role
  labels:
    app: api-gateway
    component: gateway
rules:
# Allow reading ConfigMaps and Secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Allow reading endpoints for service discovery
- apiGroups: [""]
  resources: ["endpoints", "services"]
  verbs: ["get", "list", "watch"]
# Allow reading pods for health checks
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-role-binding
  namespace: travelowkey
  labels:
    app: api-gateway
    component: gateway
subjects:
- kind: ServiceAccount
  name: api-gateway
  namespace: travelowkey
roleRef:
  kind: Role
  name: api-gateway-role
  apiGroup: rbac.authorization.k8s.io