apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: travelowkey
  labels:
    app: api-gateway
    component: gateway
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # echo -n "your-jwt-secret-key" | base64
  jwt-secret: dHJhdmVsb3drZXktc3VwZXItc2VjcmV0LWtleS10aGF0LXNob3VsZC1iZS1jaGFuZ2VkLWluLXByb2R1Y3Rpb24=
  
  # OAuth credentials (optional)
  # google-client-id: ""
  # google-client-secret: ""
  # facebook-client-id: ""
  # facebook-client-secret: ""

---
# Template for creating secrets with kubectl
# kubectl create secret generic api-gateway-secrets \
#   --from-literal=jwt-secret="your-production-jwt-secret" \
#   --from-literal=google-client-id="your-google-client-id" \
#   --from-literal=google-client-secret="your-google-client-secret" \
#   --from-literal=facebook-client-id="your-facebook-client-id" \
#   --from-literal=facebook-client-secret="your-facebook-client-secret" \
#   -n travelowkey