apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
      - name: flight-service
        image: flight-service:latest
        ports:
        - containerPort: 3000