apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-staging
  namespace: argocd
spec:
  project: travelowkey-staging
  source:
    repoURL: 'https://github.com/your-org/travelowkey'
    targetRevision: HEAD
    path: helm/user-service
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: travelowkey-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true