name: Deploy Service
on:
  push:
    branches: [main]
    paths: ['services/**', 'frontend/**', 'helm/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Backend
        run: |
          cd travelowkey/services/user-service && ./mvnw checkstyle:check || true
          cd ../../frontend && npm run lint || true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Test Backend
        run: |
          cd travelowkey/services/user-service && ./mvnw test || true
          cd ../../frontend && npm test || true

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Images
        run: |
          docker build -t ghcr.io/org/user-service:latest travelowkey/services/user-service
          docker build -t ghcr.io/org/frontend:latest travelowkey/frontend
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Images
        run: |
          docker push ghcr.io/org/user-service:latest
          docker push ghcr.io/org/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Helm Upgrade
        run: |
          helm upgrade --install travelowkey helm/travelowkey \
            --namespace travelowkey-staging --create-namespace \
            -f helm/travelowkey/values.yaml -f helm/travelowkey/values-staging.yaml